version: '3.8'
services:
  db:
    image: mysql:8.0  # MySQL 8.0 이미지 사용
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"  # 호스트와 컨테이너의 MySQL 포트 연결
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - db_data:/var/lib/mysql  # MySQL 데이터를 호스트에 저장

volumes:
  db_data: