springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

spring:
  application:
    name: bookReader

#  h2:
#    console:
#      enabled: true    # H2 Console 활성화
#      path: /h2-console  # H2 Console 경로 설정 (기본값: /h2-console)
#  datasource:
#    url: jdbc:h2:mem:testdb  # 메모리 기반 H2 데이터베이스
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    initialization-mode: always  # 초기 데이터베이스 스크립트 실행
  datasource:
    url: jdbc:mysql://mysql-container:3306/bookreader?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bookreader
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 500
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1b3a5df0f36530d4a3656efd9ec2335c
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

