name: Deploy to Vultr

on:
 push:
   branches:
     - develop

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     - name: Build Docker image
       run: |
         docker build -t bookreader-back -f Dockerfile .

     - name: Push Docker image to Vultr
       run: |
         ssh -o StrictHostKeyChecking=no root@141.164.55.202 "
         docker stop bookreader-back || true &&
         docker rm bookreader-back || true &&
         docker pull bookreader-back &&
         docker run -d --name bookreader-back -p 8080:8080 bookreader-back
