name: Deploy to Vultr

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build  -t soeha8952/bookreader-back:latest .

      - name: Push Docker image to Docker Hub
        run: docker push soeha8952/bookreader-back:latest

      - name: Deploy to Vultr
        run: |
          ssh -o StrictHostKeyChecking=no root@141.164.55.202 << 'EOF'
          docker stop bookreader-back || true
          docker rm bookreader-back || true
          docker pull soeha8952/bookreader-back:latest
          docker run -d --name bookreader-back -p 8080:8080 soeha8952/bookreader-back:latest
          EOF
